package replica

import (
	"banyan/blockchain"
)

type Safety interface {
	ProcessBlock(block *blockchain.Block) error
	ProcessNotarizationShare(vote *blockchain.NotarizationShare)
	ProcessFinalizationShare(vote *blockchain.FinalizationShare)
	// MakeProposal builds a block over a payload the replica supplies:
	// client requests drained from the mempool, or generated bytes.
	MakeProposal(height int, rank int, payload []byte) *blockchain.Block
}
