package config

import (
	"bufio"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"strconv"

	"banyan/identity"
	"banyan/log"
	"banyan/transport"
)

var configFile = flag.String("config", "config.json", "Configuration file for bamboo replica. Defaults to config.json.")

// Config contains every system configuration
type Config struct {
	Addrs     map[identity.NodeID]string `json:"address"`      // address for node communication
	HTTPAddrs map[identity.NodeID]string `json:"http_address"` // address for client server communication

	ExperimentDuration int    `json:"experiment_duration"`
	Timeout            int    `json:"timeout"`
	ByzNo              int    `json:"byzNo"`
	Strategy           string `json:"strategy"`
	PayloadSize        int    `json:"payload_size"`
	// Workload selects where block payload comes from: "generated" (the
	// fork's default — each leader fills a block with random bytes, so
	// offered load is set by payload_size alone) or "client", where blocks
	// carry real client requests drained from the mempool and payload_size
	// becomes a per-block byte budget. Empty means "generated".
	Workload string `json:"workload"`
	// MemSize bounds the per-node request queue. Beyond it a node sheds new
	// requests and tells the client, rather than absorbing unbounded backlog
	// and reporting it as latency.
	MemSize int `json:"mem_size"`
	F       int `json:"f"`
	P       int `json:"p"`
	N       int // total number of nodes

	hasher string
	signer string
}

//var keys []crypto.PrivateKey
//var pubKeys []crypto.PublicKey

// Config is global configuration singleton generated by init() func below
var Configuration Config

func init() {
	Configuration = MakeDefaultConfig()
}

// Workload modes for Config.Workload.
const (
	WorkloadGenerated = "generated"
	WorkloadClient    = "client"
)

// GetConfig returns paxi package configuration
func GetConfig() Config {
	return Configuration
}

// IsClientDriven reports whether blocks should carry client requests.
func (c Config) IsClientDriven() bool {
	return c.Workload == WorkloadClient
}

// Simulation enable go channel transportation to simulate distributed environment
func Simulation() {
	*transport.Scheme = "chan"
}

// MakeDefaultConfig returns Config object with few default values
// only used by init() and master
func MakeDefaultConfig() Config {
	return Config{
		hasher:  "sha3_256",
		signer:  "ECDSA_P256",
		MemSize: 100000,
	}
}

//func SetKeys() error {
//	keys = make([]crypto.PrivateKey, Configuration.N())
//	pubKeys = make([]crypto.PublicKey, Configuration.N())
//	var err error
//	for i := 0; i < Configuration.N(); i++ {
//		keys[i], err = crypto.GenerateKey(Configuration.signer)
//		if err != nil {
//			return err
//		}
//		pubKeys[i] = keys[i].PublicKey()
//	}
//	return nil
//}

//func (c Config) GetKeys(id int) (*crypto.PrivateKey, []crypto.PublicKey) {
//	return &keys[id], pubKeys
//}

// IDs returns all node ids
func (c Config) IDs() []identity.NodeID {
	ids := make([]identity.NodeID, 0)
	for id := range c.Addrs {
		ids = append(ids, id)
	}
	return ids
}

// GetHash returns the hashing scheme of the configuration
func (c Config) GetHashScheme() string {
	return c.hasher
}

func (c Config) GetSignatureScheme() string {
	return c.signer
}

// GetSignatureScheme returns the signing scheme of the configuration

// Z returns total number of zones
//func (c Config) Z() int {
//	return c.z
//}

// String is implemented to print the Configuration
func (c Config) String() string {
	config, err := json.Marshal(c)
	if err != nil {
		log.Error(err)
		return ""
	}
	return string(config)
}

// Load loads configuration from Configuration file in JSON format
func (c *Config) Load() {
	file, err := os.Open(*configFile)
	if err != nil {
		log.Fatal(err)
	}
	decoder := json.NewDecoder(file)
	err = decoder.Decode(c)
	if err != nil {
		log.Fatal(err)
	}

	// load ips
	ip_file, err := os.Open("ips.txt")
	if err != nil {
		fmt.Println(err)
	}
	defer ip_file.Close()

	scanner := bufio.NewScanner(ip_file)
	i := 1
	for scanner.Scan() {
		id := identity.NewNodeID(i)
		port := strconv.Itoa(3734 + i)
		addr := "tcp://" + scanner.Text() + ":" + port
		portHttp := strconv.Itoa(8069 + i)
		addrHttp := "http://" + scanner.Text() + ":" + portHttp
		c.Addrs[id] = addr
		c.HTTPAddrs[id] = addrHttp
		i++
	}

	if err := scanner.Err(); err != nil {
		fmt.Println(err)
	}

	c.N = len(c.Addrs)

	if c.MemSize <= 0 {
		c.MemSize = 100000
	}
	if c.Workload == "" {
		c.Workload = WorkloadGenerated
	}
}

// Save saves configuration to file in JSON format
func (c Config) Save() error {
	file, err := os.Create(*configFile)
	if err != nil {
		return err
	}
	encoder := json.NewEncoder(file)
	return encoder.Encode(c)
}

func (c Config) IsByzantine(id identity.NodeID) bool {
	return c.N-c.ByzNo < id.Node()
}
